### ISSUE TITLE
Is it possible to use dots with the `target` function

### ISSUE THREAD

**Issue by tysonzero** [liqula/react-hs#27]
I am currently trying to create a store action based on form data. I figured that storing the actual changing state of the form in react was overkill, since I don't care about it until the very last second when the submit button is pressed. So I was going to retrieve it from the html on submit, but `target e "form.username.value"` and similar do not seem to work. When I attach a "value" to my button and do `target e "value"` it works just fine, and when I run `document.querySelector('button').value` it gives me that same value, and `document.querySelector('button').form.username.value` gives me the value I desire. So I can only assume that the dotted notation is the problem, perhaps it is actually doing `e.target['form.username.value']` or something like that.

**Comment by fisx** [comment]
haven't checked, but your hypothesis is plausible.  i'm assuming that the desired behavior is that it translates to `e..target.form.username.value`?  i will mark this issue an enhancement, are you ok with that?

the obvious workaround is to write a foreign function that does this for you.

(it's interesting that you decided to go without even local state (as in `StatefulViewEventHandler`).  that's what i've always done so far.  it works fine, and it lets you do everything in haskell.)

**Comment by tysonzero** [comment]
Maybe I should try out `StatefulViewEventHandler`, just definitely want to avoid using a store for it. Is there any risk of a page re-render destroying my form with the current way I am doing it?

And yeah enhancement is fine, or if you know if there is a proper way to do this that would also be cool. Maybe the `.:` operator from Aeson or something? Having it desugar to `e.target['form.username.value']` is pretty reasonable, just need some way to get at those dots.

**Comment by fisx** [comment]
I don't know your code, but I suspect you're just reading from the DOM at the time the component is closed anyway, and in that case I don't expect any problems.  But I'm more convinced now that this is a job for `StatefulViewEventHandler` if you want to do it by the book.

I am going to close this; if you object, please re-open.
