### ISSUE TITLE
Tidy up TODO example

### ISSUE THREAD

**Issue by fisx** [liqula/react-hs#44]
I think the `SaveAction` type was introduced in order to make the `Action` type `NFData`-able, but that is not required any more.  (This is a small change, but the example that comes with this library should be as neat and tidy as possible.)

**Comment by tysonzero** [comment]
I can do this once it is moved into a subdirectory, don't want to break my existing PR.

**Comment by fisx** [comment]
#53 is merged!

**Comment by tysonzero** [comment]
`SaveAction` looks like it is still necessary, as if we directly use anything to do with `SomeStoreAction` we aren't going to have the necessary `Eq` instance. Which I guess comes right back to the whole #8 thing, as if we implemented that we would be able to do such a cleanup.

**Comment by fisx** [comment]
Good point, thanks!  I wrongly assume that only `NFData` had necessitated the `SaveAction` mini-DSL, but `Eq` is just as necessary a reason for it.

I will close this for now, then.
