### ISSUE TITLE
Gitter channel for react-hs

### ISSUE THREAD

**Issue by pamu** [liqula/react-hs#51]
It would be awesome to have a react-hs Gitter channel to discuss the features, issues. Also it's a great help for newbies like me to ask questions about how to get started.

**Comment by fisx** [comment]
We don't have the resources to set up and popuplate a real-time support forum.  If you want to start one, please do so; we welcome a PR with a link to it in the README.

Meanwhile, please open issues if you have support requests.

**Comment by fisx** [comment]
people keep asking about this, though.  i'm getting curious: what's needed to open a gitter channel for this?  can you do it us maintainers just quietly listening in after it's al set up?  (-:

**Comment by fisx** [comment]
@danse ping

**Comment by danse** [comment]
I believe that you have to be administrator or owner of the repo, but i'll check shortly. Gitter is nice because it keeps logs

**Comment by danse** [comment]
As an admin or owner, i think that it's just a matter of clicking a couple of buttons starting from https://gitter.im/. As far as i remember it even creates the pull request for us

**Comment by danse** [comment]
Explore > Create your own > Github projects (written small) ... but i can't

**Comment by pamu** [comment]
Click on github projects in the section "do you want to start a community for one of your github projects?"
<img width="1329" alt="screen shot 2017-08-19 at 13 30 39" src="https://user-images.githubusercontent.com/4508686/29485873-d0c1a5c2-84e2-11e7-9770-70c274afdcdb.png">

After creating gitter channel grab the badge and paste it in the readme

**Comment by pamu** [comment]
@fisx Created gitter channel and added it to readme. Sent pull request. Please feel free to join the channel on gitter at https://gitter.im/react-hs
