### ISSUE TITLE
Why are there so many default extensions.

### ISSUE THREAD

**Issue by tysonzero** [liqula/react-hs#56]
There is no way they are all being used, or are they?

**Comment by fisx** [comment]
I think they are.  Even if not, I do not see a problem with extending the language to some reasonable default extension set.

Please re-open if you know if any practical problems that arise from any of the enabled extensions.

**Comment by fisx** [comment]
while i stand by my claim that most of them are ok, i found a few that shouldn't be there.  i tweaked things a little bit in #57.  sorry for rejecting this prematurely!  please re-open if you're still unhappy about anything in particular.  (i like the fact that we have the same set of language extensions everywhere so we only need to copy&paste the whole block without adding them as needed all the time.)

**Comment by tysonzero** [comment]
Well I know for example my linter (hlint) is going to whine at me about unused language extensions, and my personal preference is to only put the necessary language extensions in each file. To me it is similar to having a bunch of unused imports.
