### ISSUE TITLE
Consider replacing type level list for dealing with props

### ISSUE THREAD

**Issue by tysonzero** [liqula/react-hs#70]
To me it seems as though using a type level list for props instead of just taking in a single argument introduces a large amount of complexity and isn't great for flexibility and reusability. It also seems to be quite different from how things like this are done in most other Haskell libraries. You can always just use a tuple or custom data type or even a heterogenous list if you want to pass in multiple values.

Is there any advantage I am missing of the current approach that we would lose? I haven't looked too thoroughly into the current implementation so there could definitely be things that I am missing.

**Comment by fisx** [comment]
thanks for raising this issue, this is bothering me, too.  i suspect this was just considered elegant when it was done, but i agree that it would be a change for the better if we could get rid of that.  would you like to try and implement this?  (-:

@wuzzeb?  @divipp?  do you have anything to add?

**Comment by tysonzero** [comment]
Will do! To me this definitely does seem like the right approach. Particularly since that is how react.js does it anyways, props is always a single argument, it can of course be an array or a dict just like it can be in Haskell.

**Comment by tysonzero** [comment]
@fisx Bump on this.
